os:
  - linux
before_install:
  - date
  - cd ${HOME}
  # Setting-up
  - export ATSHOME=${HOME}/ats-lang-anairiats-0.2.12
  - export ATSHOMERELOC=ATS-0.2.12
  - export PATSHOME=${TRAVIS_BUILD_DIR}
  - export PATH=${PATH}:${PATSHOME}/bin
  # Install pkgs
  - sudo ${TRAVIS_BUILD_DIR}/travis-ci/installpkg.sh
  # Download ATS1
  - sudo ${TRAVIS_BUILD_DIR}/travis-ci/ats1_setup.sh 0.2.12
  # Download ATS2-contrib
  - git clone https://github.com/githwxi/ATS-Postiats-contrib.git ATS-Postiats-contrib
  - export PATSHOMERELOC=${HOME}/ATS-Postiats-contrib
  - export GCC=gcc
  - export CLANG=clang
script:
  - ${GCC} --version
  - ${CLANG} --version
  # Building ATS1
  - cd ${ATSHOME}
  # ./configure&&make CC=${GCC} all
  - ./configure&&make CC=${GCC} all_ngc
  # Building ATS2
  - cd ${TRAVIS_BUILD_DIR}
  - make -f Makefile_devl CC=${GCC} all
  # make GCFLAG=-D_ATS_GCATS -f Makefile_devl CC=${GCC} all
  # make C3NSTRINTKND=intknd -f Makefile_devl CC=${CLANG} all
  # make C3NSTRINTKND=intknd GCFLAG=-D_ATS_GCATS -f Makefile_devl CC=${CLANG} all
  # Trying-out release process
  - cd ${TRAVIS_BUILD_DIR}
  - make -C ${PATSHOME}/src CBOOT
  - make -C ${PATSHOME}/src/CBOOT/prelude
  - make -C ${PATSHOME}/src/CBOOT/libc
  - make -C ${PATSHOME}/src/CBOOT/libats
  - make -C ${PATSHOME}/doc/DISTRIB atspackaging
  - make -C ${PATSHOME}/doc/DISTRIB atspacktarzvcf
  - make -C ${PATSHOME}/doc/DISTRIB cleanall
  # make -C ${PATSHOME}/doc/DISTRIB atscontribing
  # make -C ${PATSHOME}/doc/DISTRIB atscntrbtarzvcf
  # make -C ${PATSHOME}/doc/DISTRIB cleanall
  # Running regress test
  - cd ${TRAVIS_BUILD_DIR}
  - make -C ${PATSHOME}/doc -f Makefile_test testall > testall_doc.log 2>&1
  - tail -100 testall_doc.log
  # Building some utilities
  - make -C libatsynmark
  - make -C utils/atsynmark
  # Running test on ATS2-contrib
  - make -C ${PATSHOMERELOC} -f Makefile_test testall
after_script:
  - date
