os:
  - osx
  - linux
before_install:
  - date
  - cd ${HOME}
  # Setting-up
  - export ATSHOME=${HOME}/ats-lang-anairiats-0.2.11
  - export ATSHOMERELOC=ATS-0.2.11
  - export PATSHOME=${TRAVIS_BUILD_DIR}
  - export PATH=${PATH}:${PATSHOME}/bin
  # Install pkgs
  - ${TRAVIS_BUILD_DIR}/travis-ci/installpkg.sh
  # Download ATS1
  - ${TRAVIS_BUILD_DIR}/travis-ci/ats1_setup.sh 0.2.11
  # Download ATS2-contrib
  - git clone https://github.com/githwxi/ATS-Postiats-contrib.git ATS-Postiats-contrib
  - export PATSHOMERELOC=${HOME}/ATS-Postiats-contrib
script:
  # Building ATS1
  - cd ${ATSHOME}
  - gcc --version
  # ./configure&&make all
  - ./configure&&make all_ngc
  # Building ATS2
  - cd ${TRAVIS_BUILD_DIR}
  # make -f Makefile_devl all
  - make GCFLAG=-D_ATS_NGC -f Makefile_devl all
  # Trying-out release process
  - make -C ${PATSHOME}/src CBOOT
  - make -C ${PATSHOME}/src/CBOOT/prelude
  - make -C ${PATSHOME}/src/CBOOT/libc
  - make -C ${PATSHOME}/src/CBOOT/libats
  - make -C ${PATSHOME}/doc/DISTRIB atspackaging
  - make -C ${PATSHOME}/doc/DISTRIB atspacktarzvcf
  - make -C ${PATSHOME}/doc/DISTRIB cleanall
  # make -C ${PATSHOME}/doc/DISTRIB atscontribing
  # make -C ${PATSHOME}/doc/DISTRIB atscntrbtarzvcf
  # make -C ${PATSHOME}/doc/DISTRIB cleanall
  # Regress test
  - make -C ${PATSHOME}/doc -f Makefile_test testall > testall_doc.log 2>&1
  - tail -100 testall_doc.log
  # Building utils
  - make -C libatsynmark # it is moved to ATS2-contrib
  - make -C utils/atsynmark # it is moved to ATS2-contrib
  - make -C utils/packedit # it is moved to ATS2-contrib
  # Testing extensively
  - make -C ${PATSHOMERELOC} -f Makefile_test testall
after_script:
  - date
