before_install:
  - date
  - cd ${HOME}
  - sudo apt-get -qq -y update
  - sudo apt-get -qq -y install libgc-dev
  - sudo apt-get -qq -y install libgmp3-dev
  - export ATSHOME=${HOME}/ats-lang-anairiats-0.2.11
  - export ATSHOMERELOC=ATS-0.2.11
  - export PATSHOME=${TRAVIS_BUILD_DIR}
  - export PATH=${PATH}:${PATSHOME}/bin
  # Building ATS1
  - ${TRAVIS_BUILD_DIR}/travis-ci/setup.sh 0.2.11
  # Download ATS2-contrib
  - git clone https://github.com/githwxi/ATS-Postiats-contrib.git ATS-Postiats-contrib
  - export PATSHOMERELOC=${HOME}/ATS-Postiats-contrib
script:
  - cd ${TRAVIS_BUILD_DIR}
  # Testing release process
  - make -f codegen/Makefile_atslib
  - make -f Makefile_devl src_depend
  - make -C ${PATSHOME}/src patsopt
  - make -C ${PATSHOME}/src CBOOT
  - make -C ${PATSHOME}/src/CBOOT/prelude
  - make -C ${PATSHOME}/src/CBOOT/libc
  - make -C ${PATSHOME}/src/CBOOT/libats
  - make -C ${PATSHOME}/doc/DISTRIB atspackaging
  - make -C ${PATSHOME}/doc/DISTRIB cleanall
  - make -C ${PATSHOME}/doc/DISTRIB atspacktarzvcf
  # Regress test
  - make -f Makefile_devl all
  - make -C ${PATSHOME}/doc -f Makefile_test testall > testall_doc.log 2>&1
  - tail -100 testall_doc.log
  # Building utils
  - make -C libatsynmark # it is moved to ATS2-contrib
  - make -C utils/atsynmark # it is moved to ATS2-contrib
  - make -C utils/packedit # it is moved to ATS2-contrib
  # Testing extensively
  - make -C ${PATSHOMERELOC} -f Makefile_test testall
after_script:
  - date
